# Generated by Django 4.2.7 on 2023-11-02 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=200)),
                ('car_number', models.CharField(max_length=10)),
                ('car_type', models.CharField(choices=[('private', 'private'), ('public', 'public'), ('transportation', 'transportation')], default='public', max_length=30)),
                ('mobile_number', models.IntegerField()),
                ('driver_rating', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
