# Generated by Django 5.0.1 on 2024-05-03 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('uses_own_system', models.BooleanField(default=False)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=16, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('proximity', models.FloatField(default=1.0, help_text='Proximity from the nearest point of the poly line')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=16)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('driver_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_license', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=3)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_road', models.CharField(blank=True, default='مسار غير معروف', max_length=32, null=True)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(default=0.0, help_text='Distance in kilometers')),
                ('trip_status', models.CharField(default='pending', max_length=16)),
                ('available_seats', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_road', models.CharField(blank=True, default='مسار غير معروف', max_length=32, null=True)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('distance', models.FloatField(default=0.0, help_text='Distance in kilometers')),
                ('trip_status', models.CharField(default='pending', max_length=16)),
                ('available_seats', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=10, unique=True)),
                ('bus_type', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('amenities', models.JSONField(default=dict)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='mishwari_main_app.busoperator')),
            ],
        ),
        migrations.AddConstraint(
            model_name='citylist',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='Unique Coordinates'),
        ),
        migrations.AddField(
            model_name='busoperator',
            name='operational_regions',
            field=models.ManyToManyField(to='mishwari_main_app.citylist'),
        ),
        migrations.AddField(
            model_name='driver',
            name='buses',
            field=models.ManyToManyField(related_name='drivers', to='mishwari_main_app.bus'),
        ),
        migrations.AddField(
            model_name='driver',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mishwari_main_app.busoperator'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='mishwari_main_app.seat'),
        ),
        migrations.AddField(
            model_name='subtrips',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtrip_destinations', to='mishwari_main_app.citylist'),
        ),
        migrations.AddField(
            model_name='subtrips',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mishwari_main_app.driver'),
        ),
        migrations.AddField(
            model_name='subtrips',
            name='pickup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtrip_pickups', to='mishwari_main_app.citylist'),
        ),
        migrations.AddField(
            model_name='trips',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mishwari_main_app.bus'),
        ),
        migrations.AddField(
            model_name='trips',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_destinations', to='mishwari_main_app.citylist'),
        ),
        migrations.AddField(
            model_name='trips',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mishwari_main_app.driver'),
        ),
        migrations.AddField(
            model_name='trips',
            name='pickup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_pickups', to='mishwari_main_app.citylist'),
        ),
        migrations.AddField(
            model_name='subtrips',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_trips', to='mishwari_main_app.trips'),
        ),
        migrations.AddField(
            model_name='seat',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='mishwari_main_app.trips'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mishwari_main_app.trips'),
        ),
    ]
