# Generated by Django 4.2.7 on 2023-11-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
