# Generated by Django 5.0.1 on 2024-05-05 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0002_remove_booking_trip_remove_seat_trip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='object_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mishwari_main_app.trips'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='mishwari_main_app.trips'),
            preserve_default=False,
        ),
    ]
