# Generated by Django 4.2.7 on 2023-11-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0002_driver_car_photo_driver_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_license',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='standard_rate',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('trip_status', models.CharField(default='pending', max_length=16)),
                ('available_seats', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mishwari_main_app.driver')),
            ],
        ),
    ]
