# Generated by Django 5.0.1 on 2024-05-05 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0003_remove_booking_content_type_remove_booking_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mishwari_main_app.subtrips'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='mishwari_main_app.trips'),
            preserve_default=False,
        ),
    ]
