# Generated by Django 4.2.7 on 2023-11-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0003_driver_driver_license_driver_is_ac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(choices=[('SYN', 'Seiyon'), ('MKL', 'AL-Mukalla'), ('ADN', 'Aden'), ('ATQ', 'Ataq'), ('TRM', 'Tarim'), ('TAZ', 'Taiz'), ('SAN', "Sana'a"), ('QTN', 'AL-Qaten'), ('SHN', 'Shehen'), ('WDY', 'AL-Wadeiya'), ('MRB', 'Marib'), ('HDH', 'AL-Hudaidah'), ('EBB', 'Ebb'), ('BYD', 'AL-Bidaa')], max_length=16)),
                ('destination', models.CharField(choices=[('SYN', 'Seiyon'), ('MKL', 'AL-Mukalla'), ('ADN', 'Aden'), ('ATQ', 'Ataq'), ('TRM', 'Tarim'), ('TAZ', 'Taiz'), ('SAN', "Sana'a"), ('QTN', 'AL-Qaten'), ('SHN', 'Shehen'), ('WDY', 'AL-Wadeiya'), ('MRB', 'Marib'), ('HDH', 'AL-Hudaidah'), ('EBB', 'Ebb'), ('BYD', 'AL-Bidaa')], max_length=16)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='trips',
            name='trip_fare',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mishwari_main_app.tripfare'),
        ),
    ]
