# Generated by Django 4.2.7 on 2023-11-04 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0004_tripfare_alter_driver_driver_rating_trips_trip_fare'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_charger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tripfare',
            name='path_road',
            field=models.CharField(blank=True, default='unknown road', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_type',
            field=models.CharField(choices=[('mass', 'mass bus'), ('bulka', 'bulka bus')], default='public', max_length=30),
        ),
        migrations.AlterField(
            model_name='trips',
            name='trip_fare',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mishwari_main_app.tripfare'),
        ),
    ]
