# Generated by Django 5.0.1 on 2024-05-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0004_alter_booking_trip_alter_seat_trip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubTrips',
            new_name='AllTrips',
        ),
        migrations.RenameModel(
            old_name='Trips',
            new_name='MainTrip',
        ),
        migrations.AlterField(
            model_name='seat',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='mishwari_main_app.MainTrip'),
        ),
    ]
