# Generated by Django 4.2.7 on 2023-11-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0006_remove_trips_trip_fare_trips_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='standard_rate',
        ),
    ]
