# Generated by Django 5.0.1 on 2024-01-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0007_remove_driver_standard_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء')], max_length=16)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=14)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=14)),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_type',
            field=models.CharField(choices=[('جماعي', 'جماعي'), ('بلكة', 'بلكة')], default='bulka', max_length=30),
        ),
        migrations.AlterField(
            model_name='trips',
            name='destination',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء')], max_length=16),
        ),
        migrations.AlterField(
            model_name='trips',
            name='path_road',
            field=models.CharField(blank=True, default='مسار غير معروف', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='pickup',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء')], max_length=16),
        ),
    ]
