# Generated by Django 5.0.1 on 2024-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0008_citylist_alter_driver_car_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylist',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='citylist',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
