# Generated by Django 5.0.1 on 2024-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0009_booking_payment_method_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
