# Generated by Django 5.0.1 on 2024-01-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0009_alter_citylist_latitude_alter_citylist_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylist',
            name='city',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء')], max_length=16, unique=True),
        ),
    ]
