# Generated by Django 5.0.1 on 2024-01-31 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0010_alter_citylist_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء')], max_length=16)),
                ('destination', models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء')], max_length=16)),
                ('path_road', models.CharField(blank=True, default='مسار غير معروف', max_length=16, null=True)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('trip_status', models.CharField(default='pending', max_length=16)),
                ('available_seats', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mishwari_main_app.driver')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_trips', to='mishwari_main_app.trips')),
            ],
        ),
    ]
