# Generated by Django 5.0.1 on 2024-08-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0010_booking_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryMobileVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('otp_sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
