# Generated by Django 5.0.1 on 2024-02-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0011_subtrips'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtrips',
            name='distance',
            field=models.FloatField(default=0, help_text='Distance in kilometers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='distance',
            field=models.FloatField(default=0, help_text='Distance in kilometers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citylist',
            name='city',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء'), ('جعار', 'جعار'), ('رضوم', 'رضوم')], max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='subtrips',
            name='destination',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء'), ('جعار', 'جعار'), ('رضوم', 'رضوم')], max_length=16),
        ),
        migrations.AlterField(
            model_name='subtrips',
            name='pickup',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء'), ('جعار', 'جعار'), ('رضوم', 'رضوم')], max_length=16),
        ),
        migrations.AlterField(
            model_name='trips',
            name='destination',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء'), ('جعار', 'جعار'), ('رضوم', 'رضوم')], max_length=16),
        ),
        migrations.AlterField(
            model_name='trips',
            name='pickup',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء'), ('جعار', 'جعار'), ('رضوم', 'رضوم')], max_length=16),
        ),
    ]
