# Generated by Django 5.0.1 on 2024-02-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0013_alter_subtrips_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtrips',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
