# Generated by Django 5.0.1 on 2024-08-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0013_alter_profile_address_alter_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=None),
        ),
    ]
