# Generated by Django 5.0.1 on 2024-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0015_alter_trips_arrival_time_alter_trips_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylist',
            name='city',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء'), ('جعار', 'جعار'), ('رضوم', 'رضوم'), ('يريم', 'يريم'), ('ذمار', 'ذمار')], max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='subtrips',
            name='destination',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء'), ('جعار', 'جعار'), ('رضوم', 'رضوم'), ('يريم', 'يريم'), ('ذمار', 'ذمار')], max_length=16),
        ),
        migrations.AlterField(
            model_name='subtrips',
            name='path_road',
            field=models.CharField(blank=True, default='مسار غير معروف', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subtrips',
            name='pickup',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء'), ('جعار', 'جعار'), ('رضوم', 'رضوم'), ('يريم', 'يريم'), ('ذمار', 'ذمار')], max_length=16),
        ),
        migrations.AlterField(
            model_name='trips',
            name='destination',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء'), ('جعار', 'جعار'), ('رضوم', 'رضوم'), ('يريم', 'يريم'), ('ذمار', 'ذمار')], max_length=16),
        ),
        migrations.AlterField(
            model_name='trips',
            name='path_road',
            field=models.CharField(blank=True, default='مسار غير معروف', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='pickup',
            field=models.CharField(choices=[('سيئون', 'سيئون'), ('المكلا', 'المكلا'), ('عدن', 'عدن'), ('عتق', 'عتق'), ('تريم', 'تريم'), ('تعز', 'تعز'), ('صنعاء', 'صنعاء'), ('القطن', 'القطن'), ('شحن', 'شحن'), ('الوديعة', 'الوديعة'), ('مأرب', 'مأرب'), ('الحديدة', 'الحديدة'), ('إب', 'إب'), ('البيضاء', 'البيضاء'), ('جعار', 'جعار'), ('رضوم', 'رضوم'), ('يريم', 'يريم'), ('ذمار', 'ذمار')], max_length=16),
        ),
    ]
