# Generated by Django 5.0.1 on 2024-02-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishwari_main_app', '0016_alter_citylist_city_alter_subtrips_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citylist',
            name='proximity',
            field=models.FloatField(default=1.0, help_text='Proximity from the nearest point of the poly line'),
        ),
        migrations.AddConstraint(
            model_name='citylist',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='Unique Coordinates'),
        ),
    ]
