# Generated by Django 5.0.1 on 2024-08-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='reference_id',
            field=models.CharField(default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='title',
            field=models.CharField(default='unknown', max_length=16),
        ),
    ]
